### ISSUE TITLE
spark-3.0.1 dataframe wirte 失败

### ISSUE THREAD

**Issue by zyfbbd** [gaoy121/starrocks-connector-for-apache-spark#4]
spark.version：3.0.1

scala.version：2.12

starrocks：Version: 2.3.0-RC01

> Properties properties = new Properties();
> properties.put("driver", "com.mysql.jdbc.Driver");
> properties.put("user", StarRocks_USER);
> properties.put("password", StarRocks_PASS);
> dataset.write().mode(SaveMode.Append).option("batchsize", 1000).jdbc(StarRocks_URL, Md_Product_Table, properties);

Spark构建宽表Dataset，使用上述方式写starrocks失败，不知道是不支持还是什么？

**Comment by gaoy121** [comment]
> spark.version：3.0.1
> 
> scala.version：2.12
> 
> starrocks：Version: 2.3.0-RC01
> 
> > Properties properties = new Properties();
> > properties.put("driver", "com.mysql.jdbc.Driver");
> > properties.put("user", StarRocks_USER);
> > properties.put("password", StarRocks_PASS);
> > dataset.write().mode(SaveMode.Append).option("batchsize", 1000).jdbc(StarRocks_URL, Md_Product_Table, properties);
> 
> Spark构建宽表Dataset，使用上述方式写starrocks失败，不知道是不支持还是什么？

报什么错误吗？

**Comment by zyfbbd** [comment]
spark.version：3.0.1，scala.version：2.12
能提供一份基于上述配置的starrocks-connector依赖包吗？下载源码本地打包不成功。

**Comment by zyfbbd** [comment]
mdProductInfo.write().format("starrocks")
                .option("starrocks.fenodes", "10.9.7.21:8030")
                .option("starrocks.table.identifier", "engineer.md_product_info")
                .option("user", StarRocks_USER)
                .option("password", StarRocks_PASS)
                .save();

其中option参数是用FE还是BE？

使用FE后Spark构建宽表Dataset写入StarRocks异常报错显示如下：
23/01/11 11:22:59 ERROR StarRocksStreamLoad: argument 'fenodes' is illegal, value is 'null'.
Exception in thread "main" com.starrocks.connector.spark.exception.IllegalArgumentException: argument 'fenodes' is illegal, value is 'null'.
	at com.starrocks.connector.spark.rest.RestService.randomEndpoint(RestService.java:197)
	at com.starrocks.connector.spark.rest.RestService.randomBackendV3(RestService.java:481)
	at com.starrocks.connector.spark.StarRocksStreamLoad.<init>(StarRocksStreamLoad.java:89)

**Comment by gaoy121** [comment]
> mdProductInfo.write().format("starrocks") .option("starrocks.fenodes", "10.9.7.21:8030") .option("starrocks.table.identifier", "engineer.md_product_info") .option("user", StarRocks_USER) .option("password", StarRocks_PASS) .save();
> 
> 其中option参数是用FE还是BE？
> 
> 使用FE后Spark构建宽表Dataset写入StarRocks异常报错显示如下： 23/01/11 11:22:59 ERROR StarRocksStreamLoad: argument 'fenodes' is illegal, value is 'null'. Exception in thread "main" com.starrocks.connector.spark.exception.IllegalArgumentException: argument 'fenodes' is illegal, value is 'null'. at com.starrocks.connector.spark.rest.RestService.randomEndpoint(RestService.java:197) at com.starrocks.connector.spark.rest.RestService.randomBackendV3(RestService.java:481) at com.starrocks.connector.spark.StarRocksStreamLoad.(StarRocksStreamLoad.java:89)

demo里使用的是BE，用的是DateSet，端口是8040
dataset.write().format("starrocks")
                .option("starrocks.benodes",destHost + ":" + destPort)
                .option("starrocks.table.identifier", destDataBase + "." + destTable)
                //写入的重试次数，默认1次
                .option("starrocks.sink.max-retries", 3)
                //每次写入的数据条数，默认10000
                .option("starrocks.sink.batch.size", 10000)
                .option("user", destUserName)
                .option("password", destPassowrd)
                //其它选项
                //指定你要写入的字段
                //.option("starrocks.write.fields","$YOUR_FIELDS_TO_WRITE")
                .option("starrocks.max.filter.ratio",filterRatio)
                .save();

**Comment by zyfbbd** [comment]
> > mdProductInfo.write().format("starrocks") .option("starrocks.fenodes", "10.9.7.21:8030") .option("starrocks.table.identifier", "engineer.md_product_info") .option("user", StarRocks_USER) .option("password", StarRocks_PASS) .save();
> > 其中option参数是用FE还是BE？
> > 使用FE后Spark构建宽表Dataset写入StarRocks异常报错显示如下： 23/01/11 11:22:59 ERROR StarRocksStreamLoad: argument 'fenodes' is illegal, value is 'null'. Exception in thread "main" com.starrocks.connector.spark.exception.IllegalArgumentException: argument 'fenodes' is illegal, value is 'null'. at com.starrocks.connector.spark.rest.RestService.randomEndpoint(RestService.java:197) at com.starrocks.connector.spark.rest.RestService.randomBackendV3(RestService.java:481) at com.starrocks.connector.spark.StarRocksStreamLoad.(StarRocksStreamLoad.java:89)
> 
> demo里使用的是BE，用的是DateSet，端口是8040 dataset.write().format("starrocks") .option("starrocks.benodes",destHost + ":" + destPort) .option("starrocks.table.identifier", destDataBase + "." + destTable) //写入的重试次数，默认1次 .option("starrocks.sink.max-retries", 3) //每次写入的数据条数，默认10000 .option("starrocks.sink.batch.size", 10000) .option("user", destUserName) .option("password", destPassowrd) //其它选项 //指定你要写入的字段 //.option("starrocks.write.fields","$YOUR_FIELDS_TO_WRITE") .option("starrocks.max.filter.ratio",filterRatio) .save();


修改StarRocksStreamLoad， 使用 randomBackendV3就可以使用starrocks.fenodes吧？

**Comment by gaoy121** [comment]
> > > mdProductInfo.write().format("starrocks") .option("starrocks.fenodes", "10.9.7.21:8030") .option("starrocks.table.identifier", "engineer.md_product_info") .option("user", StarRocks_USER) .option("password", StarRocks_PASS) .save();
> > > 其中option参数是用FE还是BE？
> > > 使用FE后Spark构建宽表Dataset写入StarRocks异常报错显示如下： 23/01/11 11:22:59 ERROR StarRocksStreamLoad: argument 'fenodes' is illegal, value is 'null'. Exception in thread "main" com.starrocks.connector.spark.exception.IllegalArgumentException: argument 'fenodes' is illegal, value is 'null'. at com.starrocks.connector.spark.rest.RestService.randomEndpoint(RestService.java:197) at com.starrocks.connector.spark.rest.RestService.randomBackendV3(RestService.java:481) at com.starrocks.connector.spark.StarRocksStreamLoad.(StarRocksStreamLoad.java:89)
> > 
> > 
> > demo里使用的是BE，用的是DateSet，端口是8040 dataset.write().format("starrocks") .option("starrocks.benodes",destHost + ":" + destPort) .option("starrocks.table.identifier", destDataBase + "." + destTable) //写入的重试次数，默认1次 .option("starrocks.sink.max-retries", 3) //每次写入的数据条数，默认10000 .option("starrocks.sink.batch.size", 10000) .option("user", destUserName) .option("password", destPassowrd) //其它选项 //指定你要写入的字段 //.option("starrocks.write.fields","$YOUR_FIELDS_TO_WRITE") .option("starrocks.max.filter.ratio",filterRatio) .save();
> 
> 修改StarRocksStreamLoad， 使用 randomBackendV3就可以使用starrocks.fenodes吧？

使用 randomBackendV3需要配置的是starrocks.benodes
![image](https://user-images.githubusercontent.com/55279192/212579658-78592853-010c-47ef-a19d-28f72236adcc.png)
之前测试配置FE会涉及到重定向的问题，请求FE最终还是会重定向到BE上
